### PR TITLE
Add adapter for Apache Santuario message digest default provider

### PR DESCRIPTION
**Pull request by nekkiy**

### CODE REVIEW

**Comment by luisgoncalves** [comment]
Hello,

If I got it correctly, the difference between this and the default provider is the fact that BC mapper is being used. Since BC is already a dependency of the library, why not just use `JCEMapper` on the default message digest provider?

**Comment by nekkiy** [comment]
`Since BC is already a dependency of the library, why not just use JCEMapper on the default message digest provider?` - Since you don't mind, I did it
`If the provider is not BC and the algorithm is not support, there's an exception anyway...` - I still do not know how to properly solve this problem.

**Comment by luisgoncalves** [comment]
What I meant by "there's an exception anyway" is that it keeps the same behavior.

**Comment by luisgoncalves** [comment]
Looks good. However, the Travis CI build reports "abuse detected". Any idea why?

https://travis-ci.org/luisgoncalves/xades4j/requests

**Comment by luisgoncalves** [comment]
Closing to try to force Travis build

**Comment by nekkiy** [comment]
I have no ideas, because before I did not work with Travis CI

**Comment by luisgoncalves** [comment]
Are you sure about the need for `Init.init()` ? Because I have it on the different classes that can be used as entry points, namely `SignerBes` and `XadesVerifierImpl`.

**Comment by luisgoncalves** [comment]
I didn't get your last comment... What's the need for `Init.init()`? Because I have it on entry classes, such as `XadesVerifier` and `SignerBes`...

**Comment by nekkiy** [comment]
If I correctly understood `xades4j.providers.impl.HttpTimeStampTokenProviderTest` and `xades4j.providers.impl.DefaultTimeStampVerificationProviderTest` tests, it is permitted to use a separate `xades4j.providers.impl.DefaultMessageDigestProvider`. That is, outside the `XadesVerifier` and `SignerBes` classes.

**Comment by luisgoncalves** [comment]
That's only because of the tests, since in real usage scenarios the message digest provider is always used in the context of signers/verifiers. Anyway, there's no problem in having the init call there. 

Thanks for the contribution.

**Pull request merged**
