### PR TITLE
[feature/support_different_timeFormats_for_Signing] Custom Time Formats for <xades:SigningTime />

### PR DESCRIPTION
**Pull request by umutemin**
* Extended SigningTimeProperty implementation for support of different time formats
e.g. yyyy-MM-dd'T'HH:mm:ss'Z'
* Added new Parameter of SimpleDateFormat.class to SigningTimeProperty.
* Appropriate changes of the calls/usages of SigningTimeProperty

### CODE REVIEW

**Comment by luisgoncalves** [comment]
Hi @umutemin , thanks for taking time to work on xades4j.

I have a few considerations:

- XML Schema is kind of strict on the allowed [representations of xsd:datetime](https://www.w3.org/TR/xmlschema11-2/#dateTime).
- Providing a `SimpleDateFormat` makes it seem like any date string is supported, but this shouldn't be the case.
- Making `*Data` and `Xml*` classes depend on high-level property classes is a bit of a smell in terms of code organization.
- Formats such as `e.g. yyyy-MM-dd'T'HH:mm:ss'Z'` or `e.g. yyyy-MM-dd'T'HH:mm:ss.fff'Z'` can be achieved by crafting the `Calendar` instance provided to the `SigningTimeProperty`, since time-zone information is preserved by JAXB built-in date conversion. The following code results in "2020-05-01T22:30:00Z":

  ```
  Calendar c = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
  c.clear();
  c.set(2020, 4, 1, 22, 30);
  signedPropsCol.setSigningTime(new SigningTimeProperty(c));
  ```
Given the items above, I'm not sure if the changes in this PR are needed. Do you have additional use-cases?

Thanks.

**Comment by umutemin** [comment]
Hi @luisgoncalves , thanks for your input about my merge/pull request.  Please find my reply inline to your considerations below. 

> Hi @umutemin , thanks for taking time to work on xades4j.
> 
> I have a few considerations:
> 
>     * XML Schema is kind of strict on the allowed [representations of xsd:datetime](https://www.w3.org/TR/xmlschema11-2/#dateTime).
> 
>     * Providing a `SimpleDateFormat` makes it seem like any date string is supported, but this shouldn't be the case.

The whole XAdES XML schema and the classes resulted out of it are indeed very strict, not giving any possibility to craft a different format. Unfortunately in cases of document-exchanges with other instances(parsers), i have experienced in the productive field that not few of these parsers have interpreted and implemented those standards other than the xades4j library. Often there are incompatibilities because of SigningTime because of formatting. Now my aim was in this picture, to work with flexible formats to be able to serialize documents for other instances so that they could succesfully run through the document signature verification. 

> 
>     * Making `*Data` and `Xml*` classes depend on high-level property classes is a bit of a smell in terms of code organization.
> 
>     * You modified code files that were auto-generated by JAXB. A better way to implement this would be to change the JAXB bindings and/or converters, so that changes are not lost if the code is generated again.

I agree. If the merge/pull request should be relevant, the changes on those classes should be resetted and changes should be relocated in appropriate classes. 

> 
>     * Formats such as `yyyy-MM-dd'T'HH:mm:ss'Z'` or `yyyy-MM-dd'T'HH:mm:ss.fff'Z'` can be achieved by crafting the `Calendar` instance provided to the `SigningTimeProperty`, since time-zone information is preserved by JAXB's built-in date conversion. The following code results in "2020-05-01T22:30:00Z":
>       ```
>       Calendar c = Calendar.getInstance(TimeZone.getTimeZone("GMT"));
>       c.clear();
>       c.set(2020, 4, 1, 22, 30);
>       signedPropsCol.setSigningTime(new SigningTimeProperty(c));
>       ```
> 
True. I am not sure if this is documented in xades4j documentation. Could be useful for many.

> 
> Given the items above, I'm not sure if the changes in this PR are needed. Do you have additional use-cases?
As mentioned above, the reason of this merge/pull request is to extend the flexibility of library to create "failsafe" XAdES signatures for other validators/parsers in the productive field that could interpret types like xsd:DateTime not as strict as xades4j does.

All in all: great to have the library, thanks for that. 

> 
> Thanks.
Should the MR further irrelevant, let me know. 

Cheers, 
Umut

**Comment by luisgoncalves** [comment]
Hi @umutemin 

I've added the `Calendar` usages to the docs.

Regarding the changes, I understand your argument. If you implement this in a way that doesn't have the aforementioned "smells" and that plays nicely with JAXB for both marshalling and unmarshalling, I'm fine with having this feature.

**Comment by luisgoncalves** [comment]
Hi @umutemin 

Since there wasn't any more activity on this, I'm closing it.

**Pull request closed without merging**
