### PR TITLE
Xades-X-L and a xades-A support

### PR DESCRIPTION
**Pull request by tiarossi**
Extends xades4j adding xades-X-L and xades-A support

### CODE REVIEW

**Comment by luisgoncalves** [comment]
Hi,

Wow, this is a huge amount of work. I see it is based on previous work from Hubert Kario. I recall having some discussions with him at the time and we had different vision/ideas about the implementation of this support..

Since the commit list is very large, any chance you can do a brief summary of the approach and the major changes to get me started on the analysis? A simple bullet list would help.. Thanks

**Comment by tiarossi** [comment]
Hi,

As you could see the work was really based on Hubert Kario code. We have been applying his patches and started from that point just applying small fixes and certificate updates. 

So, i'm not abble to tell you an explanation about all Hubert Kario changes, but i think the main point is the replacement of XadesVerifierImpl by XadesHybridVerifierImpl and DefaultQualifyingPropertiesUnmarshaller by HybridQualifyingPropertiesUnmarshaller, classes that uses JAXB to  unmarshall  some parts of the signature properties.

As reference here are the posts where we got the patches:
https://github.com/luisgoncalves/xades4j/issues/55
https://github.com/luisgoncalves/xades4j/issues/62

**Comment by luisgoncalves** [comment]
Hi @tiarossi 

- Can  you remove the commits "Avoid version conflict with original" and "Changes for local repository update"?
- Before the update to Java 1.8, everything was running OK, right? If so, can you remove this one as well?

**Comment by tiarossi** [comment]
OK @luisgoncalves.

I'm not sure how to do that. Do i need to submit a new pull request ?

**Comment by luisgoncalves** [comment]
I think you can do the changes and push them on your fork's branch. The PR
will be updated.

**Comment by tiarossi** [comment]
Done

**Comment by luisgoncalves** [comment]
Hello @tiarossi. I've (slowly) getting back context about extended forms and all the discussions I had with Hubert. From what I've got so far, he had some requirements very specific to his use-cases.. Can you say something about your use cases?

For instance, what are the form transitions that you are using? Which form do you start with? Are you adding multiple `SignatureTimeStamp` (XAdES-T). And after that, are you going straight to XAdES-A? Do you have interoperablity scenarios?

**Comment by leandrocosta** [comment]
Hello @luisgoncalves,

We start with XAdES-EPES, then we extend it to XAdES-C, then XAdES-XL, and finally XAdES-A.
We are not adding multiple SignatureTimeStamps.
What do you mean about interoperability scenarios?

**Comment by luisgoncalves** [comment]
@leandrocosta I meant whether the generated signatures are being validated by other XADES implementations or if you are using xades4j to validate XAdES-X-L or -A created by third parties.

Thanks.

**Comment by leandrocosta** [comment]
@luisgoncalves Our XAdES-A signed documents were successfully validated by  
[ETSI Signature Conformance Checker](http://signatures-conformance-checker.etsi.org/pub/index.shtml).
We didn't try to validate XAdES-A signed documents created by third parties.

**Comment by luisgoncalves** [comment]
This is a lot of code and, from a preliminary review, it includes a lot of breaking changes. I'm merging into a feature branch and I'll keep learning about the new code to decide the next steps. 

Thank you very much - all of you - for compiling the patches and contributing back.

Since these changes were applied on top of a codebase that wasn't designed to support extended forms in the first place, if you have suggestions of things that could be different/improved in the current state of the implementation, feel free to leave them here or in a new issue.

**Pull request merged**
