### PR TITLE
Update dependencies due to CVEs

### PR DESCRIPTION
**Pull request by mjechow**
Some of the used dependencies are getting a bit old and security issues are found. 

When I try to run the tests from master I am getting 4 fails:
xades4j.production.OtherSignerTests#testSignatureAlgorithms
xades4j.production.OtherSignerTests#testSignWithManifest
xades4j.verification.OtherVerifierTests#testVerifyWithManifest
xades4j.verification.XadesVerifierImplTest#testVerifyBESExtrnlResEnrichC

After the dependency upgrade the exact same tests fail. So I am pretty sure the upgrade would work.

### CODE REVIEW

**Comment by luisgoncalves** [comment]
Can you rebase? The failure in `XadesVerifierImplTest` should be fixed.

I don't get the other failures in master. I'm running on macOS. Can you share the errors, please?

**Comment by luisgoncalves** [comment]
I've been running tests from the CLI using `mvn test` and just realized that the version of the Surefire plugin being used did not pick up some tests files! (ending in *Tests). I got the same failures now.

I couldn't find release notes for Santuario 3.0, which would be good to double-check. But I think we can go forward with this. I'll fix the failing tests later.

**Comment by mjechow** [comment]
Thanks, a lot!

**Comment by mjechow** [comment]
is there a schedule when a new release can be expected?

**Comment by luisgoncalves** [comment]
Not really. But since nothing else came up, I'll release a revision version with these upgrades. 

I'll do it early next week.

**Comment by luisgoncalves** [comment]
The new version is released. May take a while to show up on central.

**Comment by mjechow** [comment]
Thank you very much. I am releasing my lib now as well. ;-)

**Pull request merged**
